### ISSUE TITLE
Get rid of `extract`

### ISSUE THREAD

**Issue by jens1o** [preprocess/pre-deferred#1]
First of all: It looks good.

Maybe we can get around this? https://github.com/preprocess/pre-deferred/blob/master/src/macros.pre#L14

Also, Closures are (unfortunately) very slow in php, maybe we can dig around this(even when this only affects the end of the application, but this still matters e.g. in web apps)?

**Comment by assertchris** [comment]
`extract` is removed in https://github.com/preprocess/pre-deferred/pull/2

Happy for suggestions on how we can get rid of the closures.
